# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: barrier_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='barrier_server.proto',
  package='barrier',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x62\x61rrier_server.proto\x12\x07\x62\x61rrier\"\x1b\n\x07Request\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\"\x17\n\x03Res\x12\x10\n\x08res_code\x18\x01 \x01(\x05\x32\x98\x01\n\rBarrierServer\x12/\n\x0bReadyToPass\x12\x10.barrier.Request\x1a\x0c.barrier.Res\"\x00\x12(\n\x04\x45xit\x12\x10.barrier.Request\x1a\x0c.barrier.Res\"\x00\x12,\n\x08SayHello\x12\x10.barrier.Request\x1a\x0c.barrier.Res\"\x00\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='barrier.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='barrier.Request.endpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=60,
)


_RES = _descriptor.Descriptor(
  name='Res',
  full_name='barrier.Res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res_code', full_name='barrier.Res.res_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'barrier_server_pb2'
  # @@protoc_insertion_point(class_scope:barrier.Request)
  })
_sym_db.RegisterMessage(Request)

Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : 'barrier_server_pb2'
  # @@protoc_insertion_point(class_scope:barrier.Res)
  })
_sym_db.RegisterMessage(Res)



_BARRIERSERVER = _descriptor.ServiceDescriptor(
  name='BarrierServer',
  full_name='barrier.BarrierServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadyToPass',
    full_name='barrier.BarrierServer.ReadyToPass',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Exit',
    full_name='barrier.BarrierServer.Exit',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='barrier.BarrierServer.SayHello',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BARRIERSERVER)

DESCRIPTOR.services_by_name['BarrierServer'] = _BARRIERSERVER

# @@protoc_insertion_point(module_scope)
