Global:
  device: gpu
  seed: 1024

  global_batch_size: 1
  local_batch_size: 1
  micro_batch_size: 1

Engine:
  max_steps: 500000
  num_train_epochs: 1
  accumulate_steps: 
  logging_freq: 1
  eval_freq: 500
  eval_iters: 10
  mix_precision:
    use_pure_fp16: True
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 1000
    output_dir: ./output
    ckpt_dir:
