Global:
  device: gpu
  seed: 2021
  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1

Engine:
  run_mode: epoch
  max_steps: -1
  eval_freq: 1
  eval_iters: -1
  test_iters: -1
  save_load:
    save_steps: -1
    save_epoch: 1
    output_dir: ./output
    ckpt_dir:

Distributed:
  dp_degree:
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    
Model:
  use_recompute: False

Fused:
  tensor_fusion: False

Profiler:
  enable: False
  scheduler: [1, 5]
  profiler_log: profiler_log
  detailed: False


Inference:
  model_dir: ./output
  mp_degree: 1
