Global:
  device: gpu
  seed: 1024

  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1


Engine:
  max_steps: 400000
  num_train_epochs: 1
  accumulate_steps: 1
  logging_freq: 10
  eval_freq: 10000000
  eval_iters: 10000000
  mix_precision:
    use_pure_fp16: False 
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 1000
    output_dir: ./output
    ckpt_dir:


Model:
  module: "CLIPModule"
  name: "CLIP"
  fused_linear: False
  use_recompute: False

# data loader for train
Data:
  Train:
    dataset:
      name: CLIPDataset
      input_path: ./data/400m.lst
      shuffle: True
    loader:
      num_workers: 8

Fused:
  tensor_fusion: False


Optimizer:
  name: Adam
  weight_decay: 0.
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  lr:
    name: CosineAnnealingWithWarmupDecay
    decay_steps: 400000
    warmup_rate: 0.025 
    max_lr: 1.0e-4
    min_lr: 0.0
  grad_clip:
    name: "ClipGradByGlobalNorm"
    clip_norm: 1.0


Profiler:
  enable: False
  scheduler: [1, 5]
  profiler_log: profiler_log
  detailed: False


Inference:
  model_dir: ./output
  mp_degree: 1

Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
