Global:
  device: gpu
  seed: 1024

  global_batch_size: 
  local_batch_size: 8
  micro_batch_size: 8

  max_steps: 500000
  num_train_epochs: 1
  accumulate_steps:
  logging_freq: 1
  eval_freq: 500
  eval_iters: 10
  test_iters:
  mix_precision:
    enable: True
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 1000
    save_epoch: 1
    output_dir: ./output
    ckpt_dir:


Model:
  name: "GPT"
  vocab_size: 50304
  hidden_size: 1024
  num_layers: 24
  num_attention_heads: 16
  ffn_hidden_size: 4096
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: False
  recompute_granularity:
  no_recompute_layers:
  fused_linear: False
  fuse_attn_qkv: True
  sequence_parallel: False


Data:
  Eval:
    dataset:
      name: LM_Eval_Dataset
      input_dir: ./data/
      split: [949, 50, 1]
      max_seq_len: 1024
      overlapping_eval: 
    sampler:
      name: GPTBatchSampler
      shuffle: False
      drop_last: True
    loader:
      num_workers: 1
      return_list: False
      collate_fn: gpt_collate_fn


Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False


Profiler:
  enable: False
  scheduler: [1, 5]
  profiler_log: profiler_log
  detailed: False


Offline_Eval:
  eval_path: ./wikitext-103/wiki.valid.tokens
  cloze_eval: False
  overlapping_eval: 32
  batch_size: 8
  max_seq_len: 1024
  logging_freq: 10
