_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 8
  micro_batch_size: 2
  max_steps: 20000
  logging_freq: 10
  mix_precision:
    use_pure_fp16: True

Data:
  Train:
    dataset:
      split: [98,2,0]
    loader:
      num_workers: 0
  Eval:
    dataset:
      split: [98,2,0]

Model:
  vocab_size: 50304
  hidden_size: 768
  num_layers: 12
  num_attention_heads: 12
  ffn_hidden_size: 3072
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.014
  use_recompute: True
  recompute_granularity:
  no_recompute_layers:
  num_experts: 2,
  expert_interval: 2
  topk: 1
  moe_use_residual: False #True
  moe_train_capacity_factor: 1.0
  moe_eval_capacity_factor: 1.0
  moe_min_capacity: 4
  moe_token_dropping: True
  balance_loss_weight: 0.01
  enable_expert_tensor_parallelism: False


  

Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False
