_base_: ./pretrain_ernie_base_345M_single_card.yaml


Distributed:
  dp_degree: 
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False

Inference:
  model_dir: output
  mp_degree: 1

  # TensorRT:
  #   max_batch_size: 16
  #   workspace_size: 1<<30
  #   min_subgraph_size: 5
  #   precision: fp16
  #   use_static: False
  #   use_calib_mode: False
  #   collect_shape: True
  #   shape_range_info_filename: ./shape.pbtxt
