_base_: ./pretrain_ernie_base.yaml

Global:
  global_batch_size: 8
  local_batch_size: 8
  micro_batch_size: 8


Model:
  vocab_size: 18000
  hidden_size: 1024
  num_hidden_layers: 24
  num_attention_heads: 16
  intermediate_size: 3072
  hidden_act: "relu"
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 512
  type_vocab_size: 2
  initializer_range: 0.02
  pad_token_id: 0
  use_recompute: False


Data:
  Train:
    dataset:
      tokenizer_type: ernie-1.0-large-zh-cw
  Eval:
    dataset:
      tokenizer_type: ernie-1.0-large-zh-cw




Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
