#pragma once
#ifndef likely
#define likely(x) __builtin_expect((x), 1)
#endif

#ifndef unlikely
#define unlikely(x) __builtin_expect((x), 0)
#endif

#define HOMURA_REPEAT1(X) HOMURA_REPEAT_PATTERN(X)
#define HOMURA_REPEAT2(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT1(ARGS)
#define HOMURA_REPEAT3(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT2(ARGS)
#define HOMURA_REPEAT4(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT3(ARGS)
#define HOMURA_REPEAT5(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT4(ARGS)
#define HOMURA_REPEAT6(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT5(ARGS)
#define HOMURA_REPEAT7(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT6(ARGS)
#define HOMURA_REPEAT8(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT7(ARGS)
#define HOMURA_REPEAT9(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT8(ARGS)
#define HOMURA_REPEAT10(X, ARGS...) HOMURA_REPEAT_PATTERN(X) HOMURA_REPEAT9(ARGS)
