_base_: ./pretrain_gpt_345M_single_card.yaml


Model:
  module: GPTEvalModule

Compress:
  pretrained:
  Quantization:
    enable: True
    weight_quantize_type: 'abs_max'
    activation_quantize_type: 'moving_average_abs_max'
    weight_bits: 8
    activation_bits: 8
    quantizable_layer_type: ['Linear', 'ColumnParallelLinear', 'RowParallelLinear']
    onnx_format: True

Offline_Eval:
  eval_path: ./wikitext-103/wiki.valid.tokens
  cloze_eval: False
  overlapping_eval: 32
  batch_size: 8
  max_seq_len: 1024
  logging_freq: 10
