_base_: ./pretrain_gpt_base.yaml

Engine:
  save_load:
          ckpt_dir: pretrain_model

Model:
  module: GPTEvalModule
  vocab_size: 50304
  hidden_size: 4096
  num_layers: 32
  num_attention_heads: 32
  ffn_hidden_size:
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: False
  recompute_granularity:
  no_recompute_layers:
  

Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False
    
    
Offline_Eval:
  eval_path: lambada_test.jsonl
  cloze_eval: True
  overlapping_eval: 32
  batch_size: 8
  max_seq_len: 1024
  logging_freq: 10


