Global:
  device: gpu
  seed: 1024

  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1

Engine:
  max_steps: 500000
  num_train_epochs: 1
  accumulate_steps: 1
  logging_freq: 1
  eval_freq: 500
  eval_iters: 10
  mix_precision:
    use_pure_fp16: True
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 1000
    output_dir: ./output
    ckpt_dir:

Model:
  module: "GPTModule"
  name: "GPT"
  fused_linear: False


Data:
  Train:
    dataset:
      name: GPTDataset
      input_dir: ./data/paddle
      split: [949, 50, 1]
      max_seq_len: 1024
    sampler:
      name: DistributedBatchSampler
      shuffle: False
      drop_last: True
    loader:
      num_workers: 1
      return_list: False
  
  Eval:
    dataset:
      name: GPTDataset
      input_dir: ./data/paddle
      split: [949, 50, 1]
      max_seq_len: 1024
    sampler:
      name: DistributedBatchSampler
      shuffle: False
      drop_last: True
    loader:
      num_workers: 1
      return_list: False


Fused:
  tensor_fusion: False

Optimizer:
  name: AdamW
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  lr:
    name: CosineAnnealingWithWarmupDecay
    decay_steps: 360000
    warmup_rate: 0.01
    max_lr: 5.0e-5
    min_lr: 1.0e-5

Gradclip:
  name: "ClipGradByGlobalNorm"
  grad_clip: 1.0

Profiler:
  enable: False
  scheduler: [1, 5]
  profiler_log: profiler_log
  detailed: False

Inference:
  model_dir: ./output
  mp_degree: 1
