_base_: ./generation_gpt_345M_single_card.yaml


Inference:
  model_dir: output
  mp_degree: 1

Engine:
  save_load:
    ckpt_dir: output

Prune:
  enable: True
  criterion: l1_norm
  ratio: 0.125

Model:
  vocab_size: 50304
  hidden_size: 1024
  num_layers: 24
  num_attention_heads: 16
  ffn_hidden_size: 4096
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: False
  recompute_granularity:
  no_recompute_layers:

Distributed:
  dp_degree: 
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False

Data:
  Test:
    dataset:
      name: GPTDataset
      input_dir: ./large_dataset/
      split: [949, 50, 1]
      max_seq_len: 1024
    sampler:
      name: GPTBatchSampler
      shuffle: False
      drop_last: True
    loader:
      num_workers: 1
      return_list: False
      collate_fn: gpt_collate_fn
