_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1


Model:
  vocab_size: 50304
  hidden_size: 4096
  num_layers: 32
  num_attention_heads: 32
  ffn_hidden_size:
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity:
  no_recompute_layers:


Distributed:
  dp_degreei:
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 8
    sharding_stage: 2
    sharding_offload: False
    comm_overlap: True

Engine:
  max_steps: 100000
  save_load:
    save_steps: 2500
    ckpt_dir: /workspace/distill-gpt/PaddleFleetX/pretrain_model

Optimizer:
  lr:
    decay_steps: 90000
    warmup_rate: 0.00
    max_lr: 2.5e-5
    min_lr: 5.0e-6

Prune:
  enable: True
  cal_sens: False
  criterion: l1_norm
  ratio: 0.125
